### ISSUE TITLE
Vulnerability in requests 2.2.1 of srcclr/example-python

### ISSUE THREAD

**Issue by priteshmehta** [srcclr/example-python#4]
Your **requests 2.2.1** library, a direct dependency in your **srcclr/example-python** repository, is subject to vulnerability [SID-2049: Information Disclosure](https://www.ksp.ops2.srcclr.io/registry/vulnerabilities/2049).

A direct dependency is a library that is specified in your project’s requirements.txt#L4.  A vulnerability in a direct dependency can be fixed by updating the version of the library in your project and rebuilding it.

This issue was fixed in version 2.3.0. However, that version may itself be subject to [other vulnerabilities](https://www.ksp.ops2.srcclr.io/registry/libraries/167292?version=2.3.0), so there are no safe versions to upgrade to.

If you are using this library and need help in fixing the issue, we suggest you post on our [community help site|https://srcclr-help-qa.ksp.ops2.srcclr.io].

For more information on this vulnerability, please visit the [SourceClear Registry](https://www.ksp.ops2.srcclr.io/registry/vulnerabilities/2049).

**Comment by codelion** [comment]
Closing this as it was done for a test I assume.
